development:
  sessions:
    default:
      database: socreate
      hosts:
        - 127.0.0.1:27017
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ<em>URL'] %>
      options:
        skip_version_check: true
        safe: true